# Generated by Django 5.1.2 on 2024-11-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='tbl_usuarios',
            name='usu_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
